export enum CsGoRarity {
  ConsumerGrade = 'Consumer Grade',
  MilSpecGrade = 'Mil-Spec Grade',
  IndustrialGrade = 'Industrial Grade',
  Restricted = 'Restricted',
  Classified = 'Classified',
  Covert = 'Covert',
  Exceptional = 'Exceptional',
  Superior = 'Superior',
  Distinguished = 'Distinguished',
  Master = 'Master',
  BaseGrade = 'Base Grade',
  Extraordinary = 'Extraordinary',
  HighGrade = 'High Grade',
  Remarkable = 'Remarkable',
  Exotic = 'Exotic',
  Contraband = 'Contraband',
}

export enum CsGoRarityColor {
  'Consumer Grade' = '#afafaf',
  'Mil-Spec Grade' = '#1155dd',
  'Industrial Grade' = '#87c7ff',
  Restricted = '#8847ff',
  Classified = '#d32ce6',
  Covert = '#eb4b4b',
  Exceptional = '#8847ff',
  Superior = '#d32ce6',
  Distinguished = '#1155dd',
  Master = '#eb4b4b',
  'Base Grade' = '#afafaf',
  Extraordinary = '#eb4b4b',
  'High Grade' = '#1155dd',
  Remarkable = '#8847ff',
  Exotic = '#d32ce6',
  Contraband = '#f2bc4b',
}
