export enum CsGoType {
  Pistol = 'Pistol',
  SMG = 'SMG',
  Rifle = 'Rifle',
  SniperRifle = 'Sniper Rifle',
  Shotgun = 'Shotgun',
  Machinegun = 'Machinegun',
  Agent = 'Agent',
  Knife = 'Knife',
  Container = 'Container',
  Sticker = 'Sticker',
  Graffiti = 'Graffiti',
  Gloves = 'Gloves',
  MusicKit = 'Music Kit',
  Patch = 'Patch',
  Collectible = 'Collectible',
  Key = 'Key',
  Pass = 'Pass',
  Gift = 'Gift',
  Tag = 'Tag',
  Tool = 'Tool',
}
