export enum Dota2Type {
  Announcer = 'Announcer',
  Bundle = 'Bundle',
  Courier = 'Courier',
  CursorPack = 'Cursor Pack',
  Emblem = 'Emblem',
  EmoticonTool = 'Emoticon Tool',
  GemOrRune = 'Gem / Rune',
  HUDSkin = 'HUD Skin',
  League = 'League',
  LoadingScreen = 'Loading Screen',
  Misc = 'Misc',
  Music = 'Music',
  Pennant = 'Pennant',
  PlayerCard = 'Player Card',
  RetiredChest = 'Retired Chest',
  Taunt = 'Taunt',
  Terrain = 'Terrain',
  Tool = 'Tool',
  Treasure = 'Treasure',
  TreasureKey = 'TreasureKey',
  Ward = 'Ward',
  Wearable = 'Wearable',
}
