export enum Dota2Quality {
  Standard = 'Standard',
  Inscribed = 'Inscribed',
  Auspicious = 'Auspicious',
  Genuine = 'Genuine',
  Heroic = 'Heroic',
  Autographed = 'Autographed',
  Frozen = 'Frozen',
  Cursed = 'Cursed',
  Base = 'Base',
  Corrupted = 'Corrupted',
  Infused = 'Infused',
  Unusual = 'Unusual',
  Exalted = 'Exalted',
  Elder = 'Elder',
  Legacy = 'Legacy',
  Ascendant = 'Ascendant',
  Favored = 'Favored',
}
